version: '3.8'

services:
  # Servicio de API .NET
  api:
    build:
      context: ./api/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - ecommerce-network
    restart: on-failure

  # Servicio de SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password12345!"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - ecommerce-network
    restart: unless-stopped

  # Servicio de UI Angular
  ui:
    build:
      context: ./ui
      dockerfile: dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - ecommerce-network
    restart: unless-stopped

networks:
  ecommerce-network:
    driver: bridge

volumes:
  sql-data: